<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\SmartCampus.Domain\SmartCampus.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Abstractions\NewFolder\" />
    <Folder Include="Common\Abstractions\Persistence\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Features\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
