import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { MockAuthError, previewAccountApi } from '../../mocks/auth-mock'
import { buttonClass, Field, inputClass, Panel, RemotePage } from './RemoteUi'
import { roleLabel } from '../../auth/roles'

export default function AccountsPage() {
  const client = useQueryClient()
  const accounts = useQuery({ queryKey: ['remote', 'accounts'], queryFn: () => previewAccountApi.list() })
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState('Representative')
  const create = useMutation({ mutationFn: () => previewAccountApi.create(username, password, role), onSuccess: () => { setUsername(''); setPassword(''); void client.invalidateQueries({ queryKey: ['remote', 'accounts'] }) } })
  const lock = useMutation({ mutationFn: ({ id, locked }: { id: string; locked: boolean }) => previewAccountApi.setLocked(id, locked), onSettled: () => client.invalidateQueries({ queryKey: ['remote'] }) })
  return <RemotePage title="Tài khoản đại diện và Staff" description="Cấp quyền truy cập cho người đăng ký đoàn và người vận hành."><div className="grid gap-5 lg:grid-cols-2"><Panel title="Tạo tài khoản mẫu"><form className="grid gap-4" onSubmit={e => { e.preventDefault(); create.mutate() }}><Field label="Tên đăng nhập"><input className={inputClass} required value={username} onChange={e => setUsername(e.target.value)} /></Field><Field label="Mật khẩu mẫu"><input className={inputClass} required minLength={6} type="password" autoComplete="new-password" value={password} onChange={e => setPassword(e.target.value)} /></Field><Field label="Vai trò"><select className={inputClass} value={role} onChange={e => setRole(e.target.value)}><option value="Representative">Đại diện trường/đoàn</option><option value="Staff">Staff vận hành</option></select></Field><p className="text-sm">Chỉ tạo tài khoản thử trong bộ nhớ. Không dùng mật khẩu thật; tài khoản mất khi tải lại trang.</p><button className={buttonClass} disabled={create.isPending}>Tạo tài khoản</button>{create.error && <p role="alert">{create.error instanceof MockAuthError ? create.error.message : 'Không tạo được tài khoản.'}</p>}{create.isSuccess && <p role="status">Đã tạo tài khoản mẫu. Có thể đăng xuất và đăng nhập thử trong cùng tab.</p>}</form></Panel><Panel title="Tài khoản hiện có">{accounts.isPending ? <p>Đang tải…</p> : accounts.isError ? <p role="alert">Không tải được tài khoản.</p> : <ul className="space-y-4">{accounts.data.map(a => <li key={a.userId} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#dce9fb] pb-3"><div><p className="font-semibold">{a.username}</p><p className="text-sm">{roleLabel(a.role)} · {a.locked ? 'Đã khóa' : 'Đang hoạt động'}</p></div>{a.role !== 'Admin' && <button className={buttonClass} disabled={lock.isPending} onClick={() => lock.mutate({ id: a.userId, locked: !a.locked })}>{a.locked ? 'Mở khóa' : 'Khóa'}</button>}</li>)}</ul>}{lock.isError && <p role="alert">Không cập nhật được quyền truy cập.</p>}</Panel></div></RemotePage>
}
