// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCampus.Infrastructure.Persistence;

#nullable disable

namespace SmartCampus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartCampus.Domain.Entities.AMRUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("BatteryPercent")
                        .HasColumnType("float");

                    b.Property<double?>("LastLat")
                        .HasColumnType("float");

                    b.Property<double?>("LastLng")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AMRUnits");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FeedbackRating")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.AMRAssignment", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid>("AMRUnitId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("AssignedAt").HasColumnType("datetime2");
                    b.Property<Guid>("AssignedByUserId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("ClosedAt").HasColumnType("datetime2");
                    b.Property<string>("Reason").HasColumnType("nvarchar(max)");
                    b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<Guid>("TourSessionId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("AMRUnitId");
                    b.HasIndex("AssignedByUserId");
                    b.HasIndex("TourSessionId", "Status").IsUnique().HasFilter("[Status] = 'Active'");
                    b.ToTable("AMRAssignments");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Action").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<Guid>("ActorUserId").HasColumnType("uniqueidentifier");
                    b.Property<string>("ActorRole").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("AfterState").HasColumnType("nvarchar(max)");
                    b.Property<string>("BeforeState").HasColumnType("nvarchar(max)");
                    b.Property<string>("CorrelationId").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Reason").HasColumnType("nvarchar(max)");
                    b.Property<string>("Result").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<Guid>("TargetId").HasColumnType("uniqueidentifier");
                    b.Property<string>("TargetType").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("ActorUserId");
                    b.HasIndex("CorrelationId");
                    b.HasIndex("TargetType", "TargetId", "CreatedAt");
                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid>("AMRUnitId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("datetime2");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("CurrentWaypointId").HasColumnType("uniqueidentifier");
                    b.Property<string>("FailureReason").HasColumnType("nvarchar(max)");
                    b.Property<string>("LastCorrelationId").HasColumnType("nvarchar(max)");
                    b.Property<Guid?>("NextWaypointId").HasColumnType("uniqueidentifier");
                    b.Property<int>("ProgressPercent").HasColumnType("int");
                    b.Property<DateTime?>("StartedAt").HasColumnType("datetime2");
                    b.Property<string>("State").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<Guid>("TourSessionId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("AMRUnitId");
                    b.HasIndex("CurrentWaypointId");
                    b.HasIndex("NextWaypointId");
                    b.HasIndex("TourSessionId");
                    b.ToTable("Missions");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.OperationalAlert", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime?>("AcknowledgedAt").HasColumnType("datetime2");
                    b.Property<Guid?>("AcknowledgedByUserId").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("AMRUnitId").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Message").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("ResolutionNote").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("ResolvedAt").HasColumnType("datetime2");
                    b.Property<string>("Severity").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<Guid?>("TourSessionId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Type").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("AcknowledgedByUserId");
                    b.HasIndex("AMRUnitId");
                    b.HasIndex("TourSessionId");
                    b.ToTable("OperationalAlerts");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.TourTimelineEvent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Detail").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("OccurredAt").HasColumnType("datetime2");
                    b.Property<Guid>("TourSessionId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Type").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("TourSessionId", "OccurredAt");
                    b.ToTable("TourTimelineEvents");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.POI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnowledgeBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WaypointId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WaypointId")
                        .IsUnique();

                    b.ToTable("POIs");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.TourSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedAMRId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAMRId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("TourSessions");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Waypoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Waypoints");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.AMRAssignment", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.AMRUnit", "AMRUnit")
                        .WithMany()
                        .HasForeignKey("AMRUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("SmartCampus.Domain.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("SmartCampus.Domain.Entities.TourSession", "TourSession")
                        .WithMany("Assignments")
                        .HasForeignKey("TourSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("AMRUnit");
                    b.Navigation("AssignedByUser");
                    b.Navigation("TourSession");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Mission", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.AMRUnit", "AMRUnit")
                        .WithMany()
                        .HasForeignKey("AMRUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.HasOne("SmartCampus.Domain.Entities.Waypoint", "CurrentWaypoint")
                        .WithMany()
                        .HasForeignKey("CurrentWaypointId")
                        .OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("SmartCampus.Domain.Entities.Waypoint", "NextWaypoint")
                        .WithMany()
                        .HasForeignKey("NextWaypointId")
                        .OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("SmartCampus.Domain.Entities.TourSession", "TourSession")
                        .WithMany("Missions")
                        .HasForeignKey("TourSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("AMRUnit");
                    b.Navigation("CurrentWaypoint");
                    b.Navigation("NextWaypoint");
                    b.Navigation("TourSession");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.OperationalAlert", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.User", "AcknowledgedByUser")
                        .WithMany()
                        .HasForeignKey("AcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                    b.HasOne("SmartCampus.Domain.Entities.AMRUnit", "AMRUnit")
                        .WithMany()
                        .HasForeignKey("AMRUnitId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("SmartCampus.Domain.Entities.TourSession", "TourSession")
                        .WithMany("Alerts")
                        .HasForeignKey("TourSessionId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("AcknowledgedByUser");
                    b.Navigation("AMRUnit");
                    b.Navigation("TourSession");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.TourTimelineEvent", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.TourSession", "TourSession")
                        .WithMany("TimelineEvents")
                        .HasForeignKey("TourSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("TourSession");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Booking", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.TimeSlot", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCampus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Slot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.POI", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.Waypoint", "Waypoint")
                        .WithOne("POI")
                        .HasForeignKey("SmartCampus.Domain.Entities.POI", "WaypointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Waypoint");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.TimeSlot", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.Route", "Route")
                        .WithMany("TimeSlots")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.TourSession", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.AMRUnit", "AssignedAMR")
                        .WithMany()
                        .HasForeignKey("AssignedAMRId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartCampus.Domain.Entities.Booking", "Booking")
                        .WithOne("Session")
                        .HasForeignKey("SmartCampus.Domain.Entities.TourSession", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedAMR");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Waypoint", b =>
                {
                    b.HasOne("SmartCampus.Domain.Entities.Route", "Route")
                        .WithMany("Waypoints")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.TourSession", b =>
                {
                    b.Navigation("Alerts");
                    b.Navigation("Assignments");
                    b.Navigation("Missions");
                    b.Navigation("TimelineEvents");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Session");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Route", b =>
                {
                    b.Navigation("TimeSlots");

                    b.Navigation("Waypoints");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.TimeSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SmartCampus.Domain.Entities.Waypoint", b =>
                {
                    b.Navigation("POI");
                });
#pragma warning restore 612, 618
        }
    }
}
