import { useEffect, useRef, useState, type Dispatch, type SetStateAction } from 'react'
import { addTask, fleetMetrics, injectScenario, PATROL_POIS, toggleRobot, type FleetScenario, type PatrolState } from './patrol-demo'
import { askFleet, cameraPerception, eventCsv, runWhatIf, type WhatIfResult } from './fleet-analysis'
import { FleetCamera } from './FleetCamera'
export type FleetTab = 'robots' | 'tasks' | 'events' | 'metrics' | 'scenarios' | 'copilot' | 'camera' | 'whatif'
const button = 'rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-blue-500 disabled:opacity-50'
const field = 'min-w-0 rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-xs text-slate-700'
import { robotModeLabel } from './fleet-analysis'
function download(name: string, content: string, type: string) {
  const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement('a')
  link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000)
}
export function FleetPanels({ tab, state, setState, selected, setSelected }: { tab: FleetTab; state: PatrolState; setState: Dispatch<SetStateAction<PatrolState>>; selected: number; setSelected: (n: number) => void }) {
  const [point, setPoint] = useState(0), [scenario, setScenario] = useState<FleetScenario>('robot-fault')
  const [question, setQuestion] = useState(''), [messages, setMessages] = useState<ReturnType<typeof askFleet>[]>([])
  const [cctv, setCctv] = useState(false), [analysis, setAnalysis] = useState(false), [filter, setFilter] = useState('all')
  const [duration, setDuration] = useState(60), [samples, setSamples] = useState(1), [result, setResult] = useState<WhatIfResult | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const abort = useRef(false)
  useEffect(() => { abort.current = false; return () => { abort.current = true } }, [])
  const r = state.robots.find(robot => robot.number === selected)!, metrics = fleetMetrics(state)
  const alerts=state.robots.filter(robot=>robot.mode==='fault'||robot.battery<20||robot.blockedSeconds>10)
  const robots = <label className="inline-flex items-center gap-1 text-xs">Robot<select aria-label="Robot được chọn" className={field} value={selected} onChange={e => setSelected(Number(e.target.value))}>{state.robots.map(robot => <option key={robot.number} value={robot.number}>R{robot.number}</option>)}</select></label>
  const points = <label className="inline-flex items-center gap-1 text-xs">Điểm<select aria-label="Điểm mục tiêu" className={field} value={point} onChange={e => setPoint(Number(e.target.value))}>{PATROL_POIS.map(p => <option key={p.poi} value={p.poi - 1}>Điểm {p.poi}</option>)}</select></label>
  const scenarios = <label className="inline-flex items-center gap-1 text-xs">Kịch bản<select aria-label="Kịch bản thử nghiệm" className={field} value={scenario} onChange={e => setScenario(e.target.value as FleetScenario)}><option value="robot-fault">Lỗi robot</option><option value="low-battery">Pin thấp</option><option value="block-point">Người/vật cản tại điểm</option><option value="camera-outage">Mất camera</option><option value="task-burst">Tăng 6 nhiệm vụ</option><option value="recover">Khôi phục</option></select></label>
  const ask = (text: string) => { if (!text.trim()) return; setMessages(old => [askFleet(state, text, selected), ...old].slice(0, 12)); setQuestion('') }
  return <div className="border-t border-slate-200 bg-slate-50 p-3 text-xs text-slate-700" aria-label="Bảng điều phối đội robot">
    {(alerts.length>0||state.blocked.length>0||state.cameraOffline)&&<div className="mb-2 flex flex-wrap gap-2 rounded-lg bg-amber-50 p-2" aria-label="Cảnh báo đội robot">{alerts.map(robot=><button key={robot.id} className={button} onClick={()=>setSelected(robot.number)}>R{robot.number}: {robot.mode==='fault'?'lỗi':robot.battery<20?'pin thấp':'chờ tuyến'}</button>)}{state.blocked.length>0&&<span>{state.blocked.length} vùng bị chặn</span>}{state.cameraOffline&&<span>Camera offline</span>}</div>}
    {tab === 'robots' && <div><div className="mb-2 flex flex-wrap items-center gap-2">{robots}<strong style={{color:r.color}}>{robotModeLabel(r)}</strong><span>Đích {r.target + 1} · Pin {r.battery.toFixed(0)}% · {r.visits} lượt</span><button className={button} disabled={r.mode==='fault'} onClick={() => setState(s=>toggleRobot(s,selected))}>{r.mode==='paused'?'Tiếp tục robot':'Dừng robot'}</button><button className={button} onClick={() => setState(s=>injectScenario(s,'recover',selected))}>Khôi phục robot</button></div><p>Đã đi {r.travelled.toFixed(1)}m · Chờ {r.waitSeconds.toFixed(1)}s · {r.queue.length} việc trong hàng đợi · Ưu tiên R1 → R6.</p></div>}
    {tab === 'tasks' && <div><div className="mb-2 flex flex-wrap items-center gap-2">{points}<button className={button} onClick={() => setState(s=>addTask(s,point))}>Giao nhiệm vụ</button><button className={button} onClick={()=>setState(s=>injectScenario(s,'task-burst',selected,point))}>Tăng 6 nhiệm vụ</button></div><p className="mb-2 text-[10px] text-slate-500">Chọn robot có tổng điểm khoảng cách, hàng đợi và pin thấp nhất; loại robot lỗi/pin dưới 20%.</p><ul className="space-y-1" aria-label="Giải thích phân công">{state.decisions.slice(0,6).map((d,i)=><li key={i}>{d}</li>)}{!state.decisions.length&&<li>Chưa có nhiệm vụ thủ công; đội đang tuần tra ngẫu nhiên.</li>}</ul><ol className="mt-2 max-h-36 space-y-1 overflow-auto" aria-label="Hàng đợi nhiệm vụ">{[...state.tasks].reverse().slice(0,24).map(t=><li key={t.id} className="flex flex-wrap items-center gap-2"><span>#{t.id} · {t.type==='manual'?'Thủ công':'Tuần tra'} · Điểm {t.point+1}</span><button className={button} onClick={()=>setSelected(t.robot)}>R{t.robot}</button><span>{t.status==='completed'?'Hoàn thành':t.status==='queued'?'Trong hàng đợi':'Đang thực hiện'}</span><span className="text-[10px] text-slate-400">Mục tiêu {(t.deadline-t.created).toFixed(0)}s</span></li>)}</ol></div>}
    {tab === 'events' && <div><div className="mb-2 flex flex-wrap gap-2"><select aria-label="Lọc nhật ký robot" className={field} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Tất cả robot</option>{state.robots.map(robot=><option key={robot.number} value={robot.number}>R{robot.number}</option>)}</select><button className={button} onClick={()=>download('fleet-events.csv',eventCsv(state),'text/csv;charset=utf-8')}>Xuất CSV</button><button className={button} onClick={()=>download('fleet-snapshot.json',JSON.stringify(state,null,2),'application/json')}>Xuất JSON</button></div><ol className="max-h-48 space-y-1 overflow-auto" aria-label="Nhật ký sự kiện">{state.events.filter(e=>filter==='all'||String(e.robot)===filter).slice(0,50).map(e=><li key={e.sequence}><span className="mr-2 font-mono text-slate-400">{e.seconds.toFixed(1)}s</span>{e.message}</li>)}</ol><p className="mt-2 text-[10px] text-slate-500">200 sự kiện gần nhất trong phiên web; chưa có lưu trữ server.</p></div>}
    {tab === 'metrics' && <div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[['Đến điểm',metrics.visits],['Quãng đường',metrics.distance.toFixed(1)+'m'],['Thời gian chờ',metrics.waits.toFixed(1)+'s'],['Nhường đường',metrics.yields],['Đang đi',metrics.active],['Robot lỗi',metrics.faults],['Pin trung bình',metrics.averageBattery.toFixed(0)+'%'],['Hoàn thành nhiệm vụ',state.completedCount],['TB hoàn thành',state.completedCount?(state.completionTotal/state.completedCount).toFixed(1)+'s':'—'],['Đúng mục tiêu 300s',state.completedCount?(state.onTimeCount/state.completedCount*100).toFixed(0)+'%':'—'],['Thời gian di chuyển',state.seconds?(state.robots.reduce((n,robot)=>n+robot.moveSeconds,0)/state.seconds/6*100).toFixed(0)+'%':'0%'],['Nhiệm vụ/giờ',state.seconds?(state.completedCount/state.seconds*3600).toFixed(1):0]].map(([label,value])=><div key={label} className="rounded-lg border border-slate-200 bg-white p-2"><span className="text-[10px] text-slate-500">{label}</span><b className="block text-base">{value}</b></div>)}</div><div className="mt-2 rounded-lg border border-slate-200 bg-white p-2"><p className="mb-1">Lượt hoàn thành · 20 phút gần nhất</p><svg className="h-16 w-full" viewBox="0 0 300 64" preserveAspectRatio="none" role="img" aria-label="Biểu đồ nhiệm vụ hoàn thành theo thời gian"><polyline fill="none" stroke="#2563eb" strokeWidth="2" points={state.history.map((h,i)=>`${i/Math.max(1,state.history.length-1)*298+1},${62-h.completed/Math.max(1,...state.history.map(v=>v.completed))*58}`).join(' ')}/></svg></div></div>}
    {tab === 'scenarios' && <div><div className="mb-2 flex flex-wrap items-center gap-2">{robots}{points}{scenarios}<button className={button} onClick={()=>setState(s=>injectScenario(s,scenario,selected,point))}>Áp dụng kịch bản</button></div><p>Vùng chặn tồn tại 90s; pin dưới 15% tự về trạm sạc ảo tại Điểm 6/10. Robot lỗi đứng yên cho đến khi khôi phục.</p><p className="mt-1 text-[10px] text-slate-500">Các lệnh này chỉ tác động đội robot cục bộ, không gửi tới robot thật.</p></div>}
    {tab === 'copilot' && <div><div className="mb-2 flex flex-wrap gap-1">{['Tổng quan đội robot','Vì sao robot chờ?','Robot nào pin thấp?','Camera nhìn thấy gì?'].map(q=><button key={q} className={button} onClick={()=>ask(q)}>{q}</button>)}</div><form className="flex gap-2" onSubmit={e=>{e.preventDefault();ask(question)}}><input className={field+' flex-1'} aria-label="Câu hỏi Copilot" placeholder="Hỏi về R1, nhường đường, pin, nhiệm vụ…" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={500}/><button className={button} type="submit">Hỏi Copilot</button></form><div className="mt-2 max-h-48 space-y-2 overflow-auto" aria-live="polite">{messages.map((m,i)=><div className="rounded-lg border border-blue-100 bg-white p-2" key={i}><p>{m.answer}</p><div className="mt-1 flex flex-wrap gap-1">{m.robots.map(n=><button key={n} className={button} onClick={()=>setSelected(n)}>R{n}</button>)}<span className="self-center text-[10px] text-slate-400">Snapshot {m.at.toFixed(1)}s</span></div></div>)}</div><p className="mt-2 text-[10px] text-slate-500">Copilot cục bộ theo quy tắc, dùng dữ liệu đội robot hiện tại; chưa gọi LLM.</p></div>}
    {tab === 'camera' && <div><div className="mb-2 flex flex-wrap items-center gap-2">{robots}<button className={button} aria-pressed={cctv} onClick={()=>setCctv(v=>!v)}>{cctv?'Camera trên robot':'Chuyển CCTV'}</button><button className={button} onClick={()=>setAnalysis(v=>!v)}>Phân tích cảnh</button></div><FleetCamera state={state} number={selected} cctv={cctv}/>{analysis&&<p className="mt-2" role="status">Nhận biết hình học: {cameraPerception(state,selected).status} · {cameraPerception(state,selected).obstacles.map(o=>`R${o.number} cách ${o.distance.toFixed(1)}m`).join(', ')||'Không thấy robot khác'} · 270°/4m, có kiểm tra đường nhìn. Chưa dùng VLM.</p>}</div>}
    {tab === 'whatif' && <div><div className="mb-2 flex flex-wrap items-center gap-2">{robots}{points}{scenarios}<label>Thời lượng <select aria-label="Thời lượng what-if" className={field} value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={60}>1 phút</option><option value={180}>3 phút</option></select></label><label>Seed <select aria-label="Số seed what-if" className={field} value={samples} onChange={e=>setSamples(Number(e.target.value))}><option value={1}>1</option><option value={3}>3</option><option value={5}>5</option></select></label><button className={button} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const next=await runWhatIf(state,scenario,selected,point,duration,samples,undefined,()=>abort.current);if(!abort.current)setResult(next)}catch(e){if(!abort.current)setError(e instanceof Error?e.message:'Lỗi phép thử')}finally{if(!abort.current)setBusy(false)}}}>{busy?'Đang thử…':'Chạy so sánh'}</button></div><p className="text-[10px] text-slate-500">Hai bản sao cùng trạng thái/seed: baseline và kịch bản. Phép thử không sửa đội đang chạy.</p>{error&&<p role="alert">{error}</p>}{result&&<div className="mt-2 grid grid-cols-2 gap-2"><div className="rounded-lg bg-white p-2"><b>Baseline</b><p>{result.baseline.visits.toFixed(1)} lượt · {result.baseline.waits.toFixed(1)}s chờ · {result.baseline.distance.toFixed(1)}m</p></div><div className="rounded-lg bg-white p-2"><b>Kịch bản · {result.samples} seed</b><p>{result.scenario.visits.toFixed(1)} lượt · {result.scenario.waits.toFixed(1)}s chờ · {result.scenario.distance.toFixed(1)}m</p></div><p className="col-span-2">Chênh lệch lượt đến điểm: {(result.scenario.visits-result.baseline.visits).toFixed(1)}; khoảng {result.range[0]}…{result.range[1]} giữa các seed, không phải khoảng dự báo thực tế.</p></div>}</div>}
  </div>
}
